version:  "3.8"

services: 
   frontendimg:  
     build:  /root/new-docker-three-tier/frontend
     container_name : frontend
     ports :
       - "80:80"
     network_mode: 
      bridge
   backendimg:
     build: /root/new-docker-three-tier/backend
     container_name: backend
     depends_on: 
          - "frontendimg"
     ports: 
       - "8080:8080"
     network_mode: 
      bridge
